### ISSUE TITLE
User specific catalog

### ISSUE THREAD

**Issue by adriengoeller** [phlowers/mechaphlowers#47]
### Describe the current behavior

to do after #46  

### Describe the expected behavior

The user must be able to indicate where his data is located and load it. The load function then returns an instantiation of the class that will be the library with its adapter.

The user uses a load function in the data module. A generic function will read the configuration yaml. It will select the catalog type to be loaded. If the type is not available, an error will occur.
The yaml will give the location of the data and allow you to set the expected columns.

```yaml
Name: Pokemon
version: 0.1
dir: ".../.../path/to/csv"
catalog_type: FakeCatalog
```
