### ISSUE TITLE
Catalog yaml loader with type and columns checks

### ISSUE THREAD

**Issue by adriengoeller** [phlowers/mechaphlowers#48]
### Describe the current behavior

todo after #47

### Describe the expected behavior

Improve the yaml loader with column name and type validator

```yaml
Name: Pokemon
version: 0.1
dir: ".../.../path/to/csv"
catalog_type: FakeCatalog

columns:
  - Name: string
  - Type: string
  - ...
```
